parameters:
  - name: hyperparameters/work_sharing
    type: discrete
    values: [parallel_for]

  - name: hyperparameters/schedule_kind
    type: discrete
    values: [static]

  - name: hyperparameters/schedule_chunk
    type: discrete
    values: [0]

  - name: hyperparameters/task_chunk_size
    type: discrete
    values: [0]

  - name: hyperparameters/num_threads
    type: discrete
    values: [2, 3, 4, 5, 6]

  - name: hyperparameters/proc_bind
    type: discrete
    values: ["close", "spread"]

  - name: hyperparameters/places
    type: discrete
    values: [cores]

  - name: hyperparameters/wait_policy
    type: discrete
    values: [active]

  - name: hyperparameters/dynamic
    type: discrete
    values: ["false"]

  - name: hyperparameters/iterations
    type: discrete
    values: [10000000]

  - name: hyperparameters/cpu_set
    type: discrete
    values: ["0-11"]
