#!/usr/bin/env python3
"""Visualize the single-run prime counting sweep saved as CSV.

The default input is produced by run_prime_range.py:

    results/prime_once_range.csv

Example:

    python visualize_prime_range.py
    python visualize_prime_range.py --formats pdf svg png --show
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parent
DEFAULT_CSV = ROOT / "results" / "prime_once_range.csv"
DEFAULT_OUT_DIR = ROOT / "figures"

PALETTE = {
    "blue": "#0072B2",
    "orange": "#E69F00",
    "green": "#009E73",
    "red": "#D55E00",
    "purple": "#CC79A7",
    "black": "#222222",
    "gray": "#6F6F6F",
    "light_gray": "#D9D9D9",
}


@dataclass(frozen=True)
class FigureSpec:
    name: str
    fig: plt.Figure


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate figures from results/prime_once_range.csv."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=DEFAULT_CSV,
        help="Input CSV generated by run_prime_range.py.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help="Directory where figures will be written.",
    )
    parser.add_argument(
        "--formats",
        nargs="+",
        default=["pdf", "png"],
        choices=["pdf", "svg", "png"],
        help="Output formats.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=450,
        help="DPI for raster outputs.",
    )
    parser.add_argument(
        "--rolling-window",
        type=int,
        default=101,
        help="Centered rolling window used to smooth timing curves.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display figures interactively after writing them.",
    )
    return parser.parse_args()


def configure_matplotlib() -> None:
    mpl.rcParams.update(
        {
            "figure.dpi": 140,
            "savefig.dpi": 450,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.03,
            "font.family": "DejaVu Sans",
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "axes.linewidth": 0.8,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            "legend.frameon": False,
            "lines.linewidth": 1.8,
            "lines.markersize": 3.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "axes.spines.top": False,
            "axes.spines.right": False,
        }
    )


def read_prime_range(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing CSV: {csv_path}")

    df = pd.read_csv(csv_path)
    required = {"limit", "primes", "cycles", "seconds", "wall_seconds", "status"}
    missing = sorted(required.difference(df.columns))
    if missing:
        raise ValueError("Missing required column(s): " + ", ".join(missing))

    df = df[df["status"].eq("ok")].copy()
    numeric_columns = ["limit", "primes", "cycles", "seconds", "wall_seconds"]
    for col in numeric_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=numeric_columns).sort_values("limit")
    df = df.drop_duplicates(subset="limit", keep="last").reset_index(drop=True)
    if df.empty:
        raise ValueError("No successful rows found in CSV.")

    df["prime_density"] = df["primes"] / df["limit"]
    df["prime_number_theorem"] = df["limit"] / np.log(df["limit"])
    df["density_theory"] = 1.0 / np.log(df["limit"])
    df["cycles_per_limit"] = df["cycles"] / df["limit"]
    df["ns_per_limit"] = df["seconds"] * 1.0e9 / df["limit"]
    df["wall_ms"] = df["wall_seconds"] * 1.0e3
    df["measured_us"] = df["seconds"] * 1.0e6
    return df


def style_axis(ax: plt.Axes, grid_axis: str = "both") -> None:
    ax.grid(True, axis=grid_axis, color=PALETTE["light_gray"], linewidth=0.55, alpha=0.75)
    ax.set_axisbelow(True)
    ax.tick_params(length=3, width=0.7, color=PALETTE["gray"])


def human_int(value: float) -> str:
    value = float(value)
    if value >= 1_000_000:
        return f"{value / 1_000_000:g}M"
    if value >= 1_000:
        return f"{value / 1_000:g}k"
    return f"{value:g}"


def rolling_median(values: pd.Series, window: int) -> pd.Series:
    window = max(1, int(window))
    if window % 2 == 0:
        window += 1
    return values.rolling(window=window, center=True, min_periods=max(3, window // 10)).median()


def plot_prime_range(df: pd.DataFrame, rolling_window: int) -> FigureSpec:
    fig, axes = plt.subplots(2, 2, figsize=(7.4, 5.4), constrained_layout=True)
    ax_count, ax_density, ax_runtime, ax_cycles = axes.ravel()

    ax_count.plot(
        df["limit"],
        df["primes"],
        color=PALETTE["blue"],
        label="measured pi(n)",
    )
    ax_count.plot(
        df["limit"],
        df["prime_number_theorem"],
        "--",
        color=PALETTE["gray"],
        linewidth=1.2,
        label="n / log(n)",
    )
    ax_count.set_xlabel("Limit n")
    ax_count.set_ylabel("Number of primes")
    ax_count.set_title("(a) Prime-counting curve")
    ax_count.legend()
    style_axis(ax_count)

    ax_density.plot(
        df["limit"],
        df["prime_density"],
        color=PALETTE["green"],
        label="pi(n) / n",
    )
    ax_density.plot(
        df["limit"],
        df["density_theory"],
        "--",
        color=PALETTE["gray"],
        linewidth=1.2,
        label="1 / log(n)",
    )
    ax_density.set_xlabel("Limit n")
    ax_density.set_ylabel("Prime density")
    ax_density.set_title("(b) Density versus asymptotic estimate")
    ax_density.legend()
    style_axis(ax_density)

    smooth_us = rolling_median(df["measured_us"], rolling_window)
    smooth_wall = rolling_median(df["wall_ms"], rolling_window)
    ax_runtime.scatter(
        df["limit"],
        df["measured_us"],
        s=8,
        color=PALETTE["orange"],
        alpha=0.35,
        linewidth=0,
        label="measured time",
    )
    ax_runtime.plot(
        df["limit"],
        smooth_us,
        color=PALETTE["red"],
        label=f"rolling median ({rolling_window})",
    )
    ax_runtime.plot(
        df["limit"],
        smooth_wall * 1.0e3,
        color=PALETTE["purple"],
        linewidth=1.1,
        alpha=0.9,
        label="wall time rolling median",
    )
    ax_runtime.set_yscale("log")
    ax_runtime.set_xlabel("Limit n")
    ax_runtime.set_ylabel("Time (us)")
    ax_runtime.set_title("(c) Runtime growth")
    ax_runtime.legend()
    style_axis(ax_runtime)

    smooth_cycles = rolling_median(df["cycles_per_limit"], rolling_window)
    smooth_ns = rolling_median(df["ns_per_limit"], rolling_window)
    ax_cycles.plot(
        df["limit"],
        smooth_cycles,
        color=PALETTE["blue"],
        label="cycles / n",
    )
    ax_cycles_twin = ax_cycles.twinx()
    ax_cycles_twin.plot(
        df["limit"],
        smooth_ns,
        color=PALETTE["orange"],
        label="ns / n",
    )
    ax_cycles.set_xlabel("Limit n")
    ax_cycles.set_ylabel("Cycles per limit", color=PALETTE["blue"])
    ax_cycles_twin.set_ylabel("ns per limit", color=PALETTE["orange"])
    ax_cycles.set_title("(d) Normalized per-limit cost")
    style_axis(ax_cycles)
    lines, labels = ax_cycles.get_legend_handles_labels()
    twin_lines, twin_labels = ax_cycles_twin.get_legend_handles_labels()
    ax_cycles.legend(lines + twin_lines, labels + twin_labels, loc="upper right")

    max_limit = human_int(df["limit"].max())
    fig.suptitle(f"Prime sweep from n={human_int(df['limit'].min())} to n={max_limit}", y=1.02)
    return FigureSpec("figure_prime_range", fig)


def save_figure(spec: FigureSpec, out_dir: Path, formats: list[str], dpi: int) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        path = out_dir / f"{spec.name}.{fmt}"
        save_kwargs = {"format": fmt}
        if fmt == "png":
            save_kwargs["dpi"] = dpi
        spec.fig.savefig(path, **save_kwargs)
        print(f"Wrote {path}")


def main() -> None:
    args = parse_args()
    configure_matplotlib()
    df = read_prime_range(args.csv)
    spec = plot_prime_range(df, args.rolling_window)
    save_figure(spec, args.out_dir, args.formats, args.dpi)

    print(
        "Rows={rows} limit={low}..{high} primes_at_max={primes} median_wall_ms={wall:.3f}".format(
            rows=len(df),
            low=int(df["limit"].min()),
            high=int(df["limit"].max()),
            primes=int(df.loc[df["limit"].idxmax(), "primes"]),
            wall=float(df["wall_ms"].median()),
        )
    )

    if args.show:
        plt.show()
    else:
        plt.close("all")


if __name__ == "__main__":
    main()
